# Makefile.module compiles each module from its component object files

# Link all the object files into re-linkable kernel module object
../$(MODULE_NAME).mod: $(MODULE_D_OBJECTS)
	$(CROSS_COMPILE)$(DC) $(LFLAGS) -r -o $@ $(MODULE_D_OBJECTS)

# Compile each object from its corresponding source file in the source directory
$(MODULE_D_OBJECTS): %.o : $(SOURCE_DIR)/$(MODULE_NAME)/%.d
	$(CROSS_COMPILE)$(DC) $(CFLAGS) $(INCLUDES) -o $@ -c $<

